apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: myapp

spec:
  containers:
    - name: redis-container
      image: redis123
      env:
        - name: APP_ENV
          value: dev
        - name: APP_CONFIG
          valueFrom:
            configMapKeyRef:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
