apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:
    labels: #labels for the ReplicaSet
      app: myapp
      type: front-end
spec:
  template:
    metadata:
      name: myapp-prod
      labels: # labels matching the PODS
        app: myapp
        type: front-end
    spec:
      containers:
        -name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: myapp # needs to match the POD label
      type: front-end