apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP # this is the default if it isn't specified
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: my-app
    type: back-end