apiVersion: v1
kind: Service
metada:
  name: myapp-service
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
  selector:
    app: my-app # whatever the app is named in the definition file
    type: front-end # whatever the app type is specified in the definition file